const passport=require('passport')
const express = require('express')
const router = express.Router()
const userControll = require('./../controlls/userController')
const productControll = require('./../controlls/productControll')
const orderController = require('./../controlls/orderController')
router.post('/userRegister',userControll.register)
router.post('/userLogin',userControll.login)
router.post('/createProduct',productControll.create)
router.get('/showproducts',productControll.show)
router.delete('/deleteproducts/:productid',productControll.delete)
router.get('/search/:item', passport.authenticate('jwt', {session: false}),productControll.search)
router.put('/addlocation', passport.authenticate('jwt', {session: false}),userControll.addLocation)
router.put('/addwishlist/:productId', passport.authenticate('jwt', {session: false}),userControll.addWishList)
router.get('/mywishlist', passport.authenticate('jwt', {session: false}),userControll.mywishlist)
router.put('/removefromwishlist/:productId', passport.authenticate('jwt', {session: false}),userControll.removefromwishlist)
router.put('/addtocart/:productId', passport.authenticate('jwt', {session: false}),userControll.addToCart)
router.get('/mycart', passport.authenticate('jwt', {session: false}),userControll.mycart)
router.post('/removefromcart/:productId', passport.authenticate('jwt', {session: false}),userControll.removeFromCart)
router.post('/buyproduct/:productId', passport.authenticate('jwt', {session: false}),orderController.addtoOrders)
router.get('/myorders', passport.authenticate('jwt', {session: false}),orderController.myOrders)
router.put('/updateorders/:orderid', passport.authenticate('jwt', {session: false}),orderController.updateorder)


module.exports = router